version: '3.8'

volumes:
  prometheus_data:
  grafana_data:

networks:
  aw-network:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

    networks:
      - aw-network

    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    networks:
      - aw-network